FROM wisrovi/agents:gpu-slim

RUN /scripts/install/images_control.sh

RUN pip install  --no-cache-dir -r /requirements/see_image_terminal.txt
RUN pip install  --no-cache-dir -r /requirements/yolo.txt
